# Generated by Django 4.2.23 on 2025-07-26 03:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('trainers', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='이름')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="전화번호는 '+999999999' 형식으로 입력해주세요.", regex='^\\+?1?\\d{9,15}$')], verbose_name='전화번호')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='이메일')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='생년월일')),
                ('gender', models.CharField(blank=True, choices=[('M', '남성'), ('F', '여성')], max_length=1, null=True, verbose_name='성별')),
                ('address', models.TextField(blank=True, verbose_name='주소')),
                ('emergency_contact', models.CharField(blank=True, max_length=20, verbose_name='비상연락처')),
                ('membership_status', models.CharField(choices=[('active', '활성'), ('inactive', '비활성'), ('suspended', '정지'), ('expired', '만료')], default='active', max_length=20, verbose_name='회원 상태')),
                ('registration_date', models.DateField(auto_now_add=True, verbose_name='가입일')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='만료일')),
                ('notes', models.TextField(blank=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.branch', verbose_name='소속 지점')),
            ],
            options={
                'verbose_name': '회원',
                'verbose_name_plural': '회원들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PTProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='프로그램명')),
                ('program_type', models.CharField(choices=[('new', '신규'), ('long_term', '장기'), ('short_term', '단기')], max_length=20, verbose_name='프로그램 유형')),
                ('sessions', models.PositiveIntegerField(verbose_name='PT 횟수')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='가격')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.branch', verbose_name='소속 지점')),
            ],
            options={
                'verbose_name': 'PT 프로그램',
                'verbose_name_plural': 'PT 프로그램들',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MemberPTRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sessions', models.PositiveIntegerField(verbose_name='총 PT 횟수')),
                ('remaining_sessions', models.PositiveIntegerField(verbose_name='남은 PT 횟수')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='총 가격')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='결제 금액')),
                ('registration_status', models.CharField(choices=[('active', '활성'), ('completed', '완료'), ('cancelled', '취소'), ('expired', '만료')], default='active', max_length=20, verbose_name='등록 상태')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='만료일')),
                ('notes', models.TextField(blank=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member', verbose_name='회원')),
                ('pt_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.ptprogram', verbose_name='PT 프로그램')),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trainers.trainer', verbose_name='담당 트레이너')),
            ],
            options={
                'verbose_name': '회원 PT 등록',
                'verbose_name_plural': '회원 PT 등록들',
                'ordering': ['-registration_date'],
            },
        ),
    ]
