# Generated by Django 4.2.23 on 2025-07-26 03:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PTRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_date', models.DateField(verbose_name='운동 날짜')),
                ('workout_time', models.TimeField(verbose_name='운동 시간')),
                ('duration', models.PositiveIntegerField(verbose_name='실제 운동 시간 (분)')),
                ('content', models.TextField(verbose_name='운동 내용')),
                ('member_condition', models.TextField(blank=True, verbose_name='회원 상태')),
                ('trainer_notes', models.TextField(blank=True, verbose_name='트레이너 메모')),
                ('is_completed', models.BooleanField(default=False, verbose_name='완료 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member', verbose_name='회원')),
            ],
            options={
                'verbose_name': 'PT 수행 내역',
                'verbose_name_plural': 'PT 수행 내역들',
                'ordering': ['-workout_date', '-workout_time'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='예약 날짜')),
                ('start_time', models.TimeField(verbose_name='시작 시간')),
                ('end_time', models.TimeField(verbose_name='종료 시간')),
                ('duration', models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(30)], verbose_name='PT 시간 (분)')),
                ('reservation_status', models.CharField(choices=[('pending', '대기중'), ('confirmed', '확정'), ('rejected', '거절'), ('cancelled', '취소'), ('completed', '완료'), ('no_show', '노쇼')], default='pending', max_length=20, verbose_name='예약 상태')),
                ('repeat_type', models.CharField(choices=[('none', '반복 없음'), ('daily', '매일'), ('weekly', '매주'), ('monthly', '매월')], default='none', max_length=20, verbose_name='반복 유형')),
                ('repeat_end_date', models.DateField(blank=True, null=True, verbose_name='반복 종료일')),
                ('notes', models.TextField(blank=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member', verbose_name='회원')),
                ('pt_registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.memberptregistration', verbose_name='PT 등록')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainers.trainer', verbose_name='트레이너')),
            ],
            options={
                'verbose_name': 'PT 예약',
                'verbose_name_plural': 'PT 예약들',
                'ordering': ['-date', '-start_time'],
                'unique_together': {('trainer', 'date', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='ReservationChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('created', '생성'), ('confirmed', '확정'), ('rejected', '거절'), ('cancelled', '취소'), ('modified', '수정'), ('completed', '완료')], max_length=20, verbose_name='변경 유형')),
                ('changed_by', models.CharField(max_length=100, verbose_name='변경자')),
                ('previous_status', models.CharField(blank=True, max_length=20, verbose_name='이전 상태')),
                ('new_status', models.CharField(blank=True, max_length=20, verbose_name='새로운 상태')),
                ('reason', models.TextField(blank=True, verbose_name='변경 사유')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='reservations.reservation', verbose_name='예약')),
            ],
            options={
                'verbose_name': '예약 변경 로그',
                'verbose_name_plural': '예약 변경 로그들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PTRecordImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pt_records/images/', verbose_name='이미지')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='설명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('pt_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='reservations.ptrecord', verbose_name='PT 수행 내역')),
            ],
            options={
                'verbose_name': 'PT 수행 내역 이미지',
                'verbose_name_plural': 'PT 수행 내역 이미지들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='ptrecord',
            name='reservation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reservations.reservation', verbose_name='예약'),
        ),
        migrations.AddField(
            model_name='ptrecord',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainers.trainer', verbose_name='트레이너'),
        ),
    ]
