# Generated by Django 4.2.23 on 2025-07-26 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='레이아웃명')),
                ('layout_type', models.CharField(choices=[('grid', '그리드'), ('flexible', '유연한 레이아웃'), ('custom', '커스텀')], default='grid', max_length=20, verbose_name='레이아웃 유형')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('config', models.JSONField(default=dict, verbose_name='설정')),
                ('is_default', models.BooleanField(default=False, verbose_name='기본 레이아웃')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '대시보드 레이아웃',
                'verbose_name_plural': '대시보드 레이아웃들',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='위젯명')),
                ('widget_type', models.CharField(choices=[('revenue_chart', '매출 차트'), ('member_stats', '회원 통계'), ('trainer_stats', '트레이너 통계'), ('reservation_stats', '예약 통계'), ('salary_stats', '급여 통계'), ('custom_chart', '커스텀 차트'), ('data_table', '데이터 테이블'), ('metric_card', '메트릭 카드')], max_length=20, verbose_name='위젯 유형')),
                ('chart_type', models.CharField(blank=True, choices=[('line', '선 그래프'), ('bar', '막대 그래프'), ('pie', '파이 차트'), ('doughnut', '도넛 차트'), ('area', '영역 그래프'), ('scatter', '산점도')], max_length=20, verbose_name='차트 유형')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('data_source', models.CharField(max_length=100, verbose_name='데이터 소스')),
                ('config', models.JSONField(default=dict, verbose_name='설정')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='정렬 순서')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '대시보드 위젯',
                'verbose_name_plural': '대시보드 위젯들',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='리포트명')),
                ('report_type', models.CharField(choices=[('revenue', '매출 리포트'), ('member', '회원 리포트'), ('trainer', '트레이너 리포트'), ('reservation', '예약 리포트'), ('salary', '급여 리포트'), ('custom', '커스텀 리포트')], max_length=20, verbose_name='리포트 유형')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('query', models.TextField(verbose_name='쿼리')),
                ('parameters', models.JSONField(default=dict, verbose_name='매개변수')),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV'), ('json', 'JSON')], default='pdf', max_length=10, verbose_name='출력 형식')),
                ('schedule', models.CharField(blank=True, max_length=100, verbose_name='스케줄')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '리포트',
                'verbose_name_plural': '리포트들',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(max_length=20, verbose_name='사용자 유형')),
                ('user_id', models.PositiveIntegerField(verbose_name='사용자 ID')),
                ('config', models.JSONField(default=dict, verbose_name='설정')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboards.dashboardlayout', verbose_name='레이아웃')),
            ],
            options={
                'verbose_name': '사용자 대시보드',
                'verbose_name_plural': '사용자 대시보드들',
                'ordering': ['user_type', 'user_id'],
            },
        ),
        migrations.CreateModel(
            name='UserDashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_x', models.PositiveIntegerField(verbose_name='X 위치')),
                ('position_y', models.PositiveIntegerField(verbose_name='Y 위치')),
                ('width', models.PositiveIntegerField(verbose_name='너비')),
                ('height', models.PositiveIntegerField(verbose_name='높이')),
                ('is_visible', models.BooleanField(default=True, verbose_name='표시 여부')),
                ('config', models.JSONField(default=dict, verbose_name='위젯 설정')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('user_dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboards.userdashboard', verbose_name='사용자 대시보드')),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboards.dashboardwidget', verbose_name='위젯')),
            ],
            options={
                'verbose_name': '사용자 대시보드 위젯',
                'verbose_name_plural': '사용자 대시보드 위젯들',
                'ordering': ['position_y', 'position_x'],
                'unique_together': {('user_dashboard', 'widget')},
            },
        ),
        migrations.AddField(
            model_name='userdashboard',
            name='widgets',
            field=models.ManyToManyField(through='dashboards.UserDashboardWidget', to='dashboards.dashboardwidget', verbose_name='위젯들'),
        ),
        migrations.CreateModel(
            name='ReportExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executed_by', models.CharField(max_length=100, verbose_name='실행자')),
                ('status', models.CharField(choices=[('pending', '대기중'), ('running', '실행중'), ('completed', '완료'), ('failed', '실패'), ('cancelled', '취소')], default='pending', max_length=20, verbose_name='상태')),
                ('parameters', models.JSONField(default=dict, verbose_name='실행 매개변수')),
                ('result_file', models.FileField(blank=True, null=True, upload_to='reports/', verbose_name='결과 파일')),
                ('error_message', models.TextField(blank=True, verbose_name='오류 메시지')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='시작일시')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='완료일시')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboards.report', verbose_name='리포트')),
            ],
            options={
                'verbose_name': '리포트 실행',
                'verbose_name_plural': '리포트 실행들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='userdashboard',
            unique_together={('user_type', 'user_id')},
        ),
    ]
