# Generated by Django 4.2.23 on 2025-07-26 03:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='년도')),
                ('month', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='월')),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='기본급')),
                ('incentive_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='인센티브')),
                ('additional_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='추가매출')),
                ('other_costs', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='기타비용')),
                ('total_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='총 급여')),
                ('payment_status', models.CharField(choices=[('pending', '대기중'), ('paid', '지급완료'), ('cancelled', '취소')], default='pending', max_length=20, verbose_name='지급 상태')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='지급일')),
                ('notes', models.TextField(blank=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainers.trainer', verbose_name='트레이너')),
            ],
            options={
                'verbose_name': '급여',
                'verbose_name_plural': '급여들',
                'ordering': ['-year', '-month'],
                'unique_together': {('trainer', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='OtherCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_type', models.CharField(choices=[('insurance', '보험료'), ('tax', '세금'), ('deduction', '공제'), ('penalty', '벌금'), ('other', '기타')], max_length=20, verbose_name='비용 유형')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='금액')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('salary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_cost_items', to='salaries.salary', verbose_name='급여')),
            ],
            options={
                'verbose_name': '기타비용',
                'verbose_name_plural': '기타비용들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncentiveDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incentive_type', models.CharField(choices=[('pt_session', 'PT 세션'), ('new_member', '신규 회원'), ('retention', '회원 유지'), ('sales', '매출'), ('other', '기타')], max_length=20, verbose_name='인센티브 유형')),
                ('quantity', models.PositiveIntegerField(verbose_name='수량')),
                ('unit_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='단가')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='총 금액')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('salary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incentive_details', to='salaries.salary', verbose_name='급여')),
            ],
            options={
                'verbose_name': '인센티브 상세',
                'verbose_name_plural': '인센티브 상세들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdditionalRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue_type', models.CharField(choices=[('supplement_sales', '보충제 판매'), ('equipment_sales', '운동용품 판매'), ('consultation', '상담료'), ('other', '기타')], max_length=20, verbose_name='매출 유형')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='금액')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('salary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_revenues', to='salaries.salary', verbose_name='급여')),
            ],
            options={
                'verbose_name': '추가매출',
                'verbose_name_plural': '추가매출들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BranchRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='년도')),
                ('month', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='월')),
                ('pt_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='PT 매출')),
                ('membership_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='회원권 매출')),
                ('additional_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='추가 매출')),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='총 매출')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.branch', verbose_name='지점')),
            ],
            options={
                'verbose_name': '지점 매출',
                'verbose_name_plural': '지점 매출들',
                'ordering': ['-year', '-month'],
                'unique_together': {('branch', 'year', 'month')},
            },
        ),
    ]
