# Generated by Django 4.2.23 on 2025-07-26 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('reservation_request', '예약 요청'), ('reservation_confirmed', '예약 확정'), ('reservation_rejected', '예약 거절'), ('reservation_cancelled', '예약 취소'), ('reservation_reminder', '예약 알림'), ('pt_completed', 'PT 완료'), ('salary_paid', '급여 지급'), ('system', '시스템 알림')], max_length=30, verbose_name='알림 유형')),
                ('recipient_type', models.CharField(max_length=20, verbose_name='수신자 유형')),
                ('recipient_id', models.PositiveIntegerField(verbose_name='수신자 ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('message', models.TextField(verbose_name='메시지')),
                ('priority', models.CharField(choices=[('low', '낮음'), ('medium', '보통'), ('high', '높음'), ('urgent', '긴급')], default='medium', max_length=10, verbose_name='우선순위')),
                ('status', models.CharField(choices=[('pending', '대기중'), ('sent', '전송완료'), ('failed', '전송실패'), ('read', '읽음')], default='pending', max_length=20, verbose_name='상태')),
                ('kakao_sent', models.BooleanField(default=False, verbose_name='카카오톡 전송')),
                ('kakao_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='카카오톡 전송일시')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='읽음 처리일시')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('related_reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.reservation', verbose_name='관련 예약')),
            ],
            options={
                'verbose_name': '알림',
                'verbose_name_plural': '알림들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='템플릿명')),
                ('notification_type', models.CharField(choices=[('reservation_request', '예약 요청'), ('reservation_confirmed', '예약 확정'), ('reservation_rejected', '예약 거절'), ('reservation_cancelled', '예약 취소'), ('reservation_reminder', '예약 알림'), ('pt_completed', 'PT 완료'), ('salary_paid', '급여 지급'), ('system', '시스템 알림')], max_length=30, verbose_name='알림 유형')),
                ('title_template', models.CharField(max_length=200, verbose_name='제목 템플릿')),
                ('message_template', models.TextField(verbose_name='메시지 템플릿')),
                ('kakao_template_id', models.CharField(blank=True, max_length=100, verbose_name='카카오톡 템플릿 ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '알림 템플릿',
                'verbose_name_plural': '알림 템플릿들',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(max_length=20, verbose_name='사용자 유형')),
                ('user_id', models.PositiveIntegerField(verbose_name='사용자 ID')),
                ('notification_type', models.CharField(max_length=30, verbose_name='알림 유형')),
                ('channel', models.CharField(choices=[('kakao', '카카오톡'), ('email', '이메일'), ('sms', 'SMS'), ('push', '푸시 알림')], max_length=20, verbose_name='알림 채널')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '알림 설정',
                'verbose_name_plural': '알림 설정들',
                'ordering': ['user_type', 'user_id'],
                'unique_together': {('user_type', 'user_id', 'notification_type', 'channel')},
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('kakao_success', '카카오톡 성공'), ('kakao_failed', '카카오톡 실패'), ('email_success', '이메일 성공'), ('email_failed', '이메일 실패'), ('sms_success', 'SMS 성공'), ('sms_failed', 'SMS 실패')], max_length=20, verbose_name='로그 유형')),
                ('recipient', models.CharField(max_length=100, verbose_name='수신자')),
                ('message', models.TextField(verbose_name='전송 메시지')),
                ('response', models.TextField(blank=True, verbose_name='응답')),
                ('error_message', models.TextField(blank=True, verbose_name='오류 메시지')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='notifications.notification', verbose_name='알림')),
            ],
            options={
                'verbose_name': '알림 로그',
                'verbose_name_plural': '알림 로그들',
                'ordering': ['-created_at'],
            },
        ),
    ]
